services:
  app:
    build:
      context: .
      target: production
    depends_on:
      - database
    networks:
      - default
  database:
    image: mariadb:10.5
    expose:
      - 3306
    environment:
      MARIADB_ROOT_PASSWORD: "${DATABASE_PASSWORD-root}"
      MARIADB_DATABASE: "${DATABASE_NAME-nfse_curitiba}"
      MARIADB_USER: '${DATABASE_USER-nfse_curitiba}'
    networks:
      - default
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:


networks:
  default:
    driver: bridge
